// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransactionManager.Persistence;

#nullable disable

namespace TransactionManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240803141750_ChangedEntityColumnTypes")]
    partial class ChangedEntityColumnTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransactionManager.Entities.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransactionTimezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId")
                        .HasName("PRIMARY");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
